---
title: "R Notebook"
output: html_notebook
---

```{r}
library(class)
library(caret)
library(e1071)
library(tidyverse)
```


```{r}
Titanic_Train = read.csv("C:/Users/bfreeman/Desktop/Test/MSDS_6306_Doing-Data-Science/Unit 6/titanic_train.csv",header = TRUE,stringsAsFactors=FALSE)

Titanic_Test = read.csv("C:/Users/bfreeman/Desktop/Test/MSDS_6306_Doing-Data-Science/Unit 6/titanic_test.csv",header = TRUE,stringsAsFactors=FALSE)

sapply(Titanic_Train,class)
sapply(Titanic_Test,class)
```

```{r}
Titanic_Train_Clean<- na.omit(Titanic_Train)
Titanic_Test_Clean<- na.omit(Titanic_Test)
Titanic_Train_Clean
Titanic_Test_Clean
```

```{r}
Titanic_Train_Clean %>% ggplot(aes(x = Pclass, y = Age , color = Survived)) + geom_point()
```

```{r}
Titanic_Train_Clean$Survived = factor(Titanic_Train_Clean$Survived,labels = c("Died","Survived"))

Titanic_Train_Clean$Survived
```

```{r}
TTrain<- Titanic_Train_Clean[c("Pclass","Age","Survived")]
TTest<- Titanic_Test_Clean[c("Pclass","Age")]

test <- 1:331

TTrain.T <- TTrain[test,]

dim(TTrain.T)
dim(TTest)
```

```{r}


confusionMatrix(table(knn.cv(TTrain.T[,c(1,2)],TTrain.T$Survived, k = 10), TTrain.T $Survived))

QOI1 = data.frame(Age = 29, Pclass = 1)
QOI2 = data.frame(Age = 29, Pclass = 2)
QOI3 = data.frame(Age = 29, Pclass = 3)
knn(TTrain[,c(1,2)],QOI1,TTrain$Survived, prob = TRUE, k = 10)
knn(TTrain[,c(1,2)],QOI2,TTrain$Survived, prob = TRUE, k = 10)
knn(TTrain[,c(1,2)],QOI3,TTrain$Survived, prob = TRUE, k = 10)

classifications = knn(TTrain.T[,c(1,2)],TestT[,c(1,2)],TTrain.T$Survived, prob = TRUE, k = 10)
confusionMatrix(classifications,TTrain.T$Survived)

```
```{r}
#Use a 70 - 30 train/test split to use cross validation to
#tune the hyperparameter k


# Loop for many k and the average of many training / test partition

set.seed(1)
iterations = 500
numks = 60
splitPerc = .95

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  trainIndices = sample(1:dim(iris)[1],round(splitPerc * dim(iris)[1]))
  train = iris[trainIndices,]
  test = iris[-trainIndices,]
  for(i in 1:numks)
  {
    classifications = knn(train[,c(1,3)],test[,c(1,3)],train$Species, prob = TRUE, k = i)
    table(classifications,test$Species)
    CM = confusionMatrix(table(classifications,test$Species))
    masterAcc[j,i] = CM$overall[1]
  }
  
}

MeanAcc = colMeans(masterAcc)

plot(seq(1,numks,1),MeanAcc, type = "l")

which.max(MeanAcc)
max(MeanAcc)



# FOR LIVE SESSION LEAVE 1 OUT KNN IRIS

set.seed(1)
iterations = 500
numks = 90

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  
  for(i in 1:numks)
  {
    CM = confusionMatrix(table(iris[,5],knn.cv(iris[,c(1,2)],iris[,5],k = i)))
    masterAcc[j,i] = CM$overall[1]
    
  }
  
}

MeanAcc = colMeans(masterAcc)

plot(seq(1,numks,1),MeanAcc, type = "l")

which.max(MeanAcc)
max(MeanAcc)
```

